#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->addCommands([
    new \AhmetBarut\PasteCli\StoreCommand(),
]);
$application->run();